 version: 2
 jobs:
   build:
     working_directory: ~/demotests
     docker:
       - image: circleci/node
       - image: selenium/standalone-chrome
     steps:
       - checkout
       - run: npm install
       - run: chmod 755 ./bin/lint
       - run: ./bin/lint
       - run: ./node_modules/.bin/codeceptjs run --reporter mochawesome
       - store_artifacts:
           path: ./output
           destination: output
